spring:
  application:
    name: jenkins-mcp-server
  ai:
    mcp:
      server:
        protocol: streamable

jenkins:
  base-url: https://jenkins-cicd.solutions.corelogic.com
  username: ${USERNAME}
  password: ${PASSWORD}
  api-paths:
    business-unit-job: credit-us
    project-space-job: pbs
  project-specific-jobs:
    - pbs-bureau-communicator
    - bps-coordinator
    - pbs-input-converter
    - pbs-output-converter
    - pbs-processor
    - pbs-output-handler
    - pbs-am-output-handler
    - pbs-am-input-handler
    - pbs-bureau-simulator
    - pbs-common
    - customer-support-tool
  common-jobs:
    build-release:
      - name: build-release
        description: to manage application deployments
    self-service:
      - name: kf-cli-execution
        description: to manage k8s instances in kf platform
      - name: cntv-cli-execution
        description: to manage k8s instances in cntv platform
      - name: veracodescan-ondemand
        description: to manage veracode scans

  integration:
    github:
      repos:
        - credit_us-pbs-bureau_communicator
        - credit_us-pbs-coordinator
        - credit_us-pbs-input_converter
        - credit_us-pbs-output_converter
        - credit_us-pbs-processor
        - credit_us-pbs-output_handler
        - credit_us-pbs-am_output_handler
        - credit_us-pbs-am_input_handler
        - credit_us-pbs-bureau_simulator
        - credit_us-pbs-common




